// Generated by scripts/resize-photos.mjs — do not edit by hand.
//
// One stamp per month, hashed from the photographs that shipped for it.
// lib/photo-edition.ts appends it to every image request, so replacing a
// photograph changes its URL and no cache can hold on to the old one.
export const photoEditions: Record<string, string> = {
  "2024-09": "dc03bb2d",
  "2024-10": "dd5a1a7d",
  "2024-11": "09daade2",
  "2024-12": "2c8340eb",
  "2025-01": "8a75b169",
  "2025-02": "5d836cf0",
  "2025-03": "b85ef3c0",
  "2025-04": "6c7b9bf9",
  "2025-05": "3c5157e4",
  "2025-06": "99cbd90d",
  "2025-07": "a6460e2d",
  "2025-08": "438dc0ae",
  "2025-09": "9d138902",
  "2025-10": "1a1eb716",
  "2025-11": "641951f3",
  "2025-12": "371191e4",
  "2026-01": "fb78eb09",
  "2026-02": "eb3da47c",
  "2026-03": "7aafa4b2",
  "2026-04": "435f48f0",
  "2026-05": "7cfb50cf",
  "2026-06": "470b2bfd",
  "2026-07": "2b118bff",
  "2026-08": "995cd038",
};
