/**
 * All site content lives here — static, hand-authored, no CMS.
 *
 * A month is a list of *events*. An event is one thing that happened: it has
 * its own cover photograph — that is the card that flies past in the run — and
 * its own set of photographs, which exist nowhere else on the page and are
 * only pulled in when the reader taps that card open. Two events in the same
 * month share nothing but the month.
 *
 * Photos are currently placeholders generated by scripts/generate-placeholders.mjs
 * (which reads this file, so the two can never drift). When real photos replace
 * them, resize to ~1500-2000px on the longest edge first (see REQUIREMENTS.md
 * performance rules) — the covers become WebGL textures and full-size originals
 * burn GPU memory for nothing.
 */

export interface MemoryPhoto {
  id: string;
  src: string; // path under /public/images/...
  alt: string;
  caption?: string; // printed into this photo's own card; falls back to the event title
}

export interface MemoryEvent {
  id: string; // "2024-09/bridge" — unique across the site
  monthId: string; // "2024-09"
  slug: string; // "bridge" — the folder its photos live in
  title: string; // printed into the card that flies in the run
  cover: MemoryPhoto; // the card in the run
  photos: MemoryPhoto[]; // the deck behind it — loaded only when it opens
  date?: string;
  location?: string;
  notes?: string; // longer story text for this event
}

export interface Month {
  id: string; // "2024-03"
  year: number; // 2024
  monthIndex: number; // 1-12
  monthLabel: string; // "March"
  title: string; // short milestone title, e.g. "Our First Trip"
  summary: string; // 1-2 sentence teaser shown in the DOM overlay
  events: MemoryEvent[]; // one card each in the run
  date?: string; // specific date, if there's one headline event
  location?: string;
  notes?: string; // longer story text
}

export interface YearBlock {
  year: number;
  label: string; // "Year One"
  months: Month[];
}

const MONTH_NAMES = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];

/** The run starts here and covers every month since, with no gaps. */
const START_YEAR = 2024;
const START_MONTH = 9;
const MONTH_COUNT = 24;

/** How an event is authored. Its photographs are placeholders until real ones land. */
interface WrittenEvent {
  slug: string;
  title: string;
  /** Photographs behind the cover while the pictures are placeholders. */
  photos?: number;
  date?: string;
  location?: string;
  notes?: string;
}

interface WrittenMonth {
  title?: string;
  summary?: string;
  date?: string;
  location?: string;
  notes?: string;
  events?: WrittenEvent[];
}

/** Photographs an event has behind its cover, before any are authored. */
const DEFAULT_EVENT_PHOTOS = 4;

/**
 * The months that have been written.
 *
 * Everything else in the two years is generated below as a placeholder, so the
 * timeline is continuous from the first month to the last — an unwritten month
 * is a month waiting to be written, not a month missing from the story. An
 * unwritten month gets a single blank event, so it is one card in the run;
 * a written month gets one card per event it names. Replace an entry here as
 * each one gets its photos and its text.
 */
const written: Record<string, WrittenMonth> = {
  "2024-09": {
    title: "The First Night",
    summary:
      "A coffee that was supposed to take an hour and somehow took until the trams stopped running.",
    date: "2024-09-14",
    location: "Prague",
    notes:
      "Neither of us remembers who suggested walking to the river. What we do remember is standing on the bridge arguing about whether the swans were asleep, and the exact moment it stopped feeling like a first date.",
    events: [
      {
        slug: "the-coffee",
        title: "The Coffee That Wasn't",
        date: "2024-09-14",
        location: "Prague",
        photos: 4,
        notes: "One hour, we said. The café closed around us and we stayed at the table anyway.",
      },
      {
        slug: "the-bridge",
        title: "Swans, Asleep",
        location: "Prague",
        photos: 4,
        notes: "The argument about whether swans sleep standing up is still not settled.",
      },
    ],
  },
  "2024-12": {
    title: "Rain and Ramen",
    summary: "The grey month. We stayed inside and made it the best one anyway.",
    events: [
      { slug: "ramen", title: "Ramen at Midnight", photos: 4 },
      { slug: "grey-walk", title: "The Grey Walk", photos: 3 },
    ],
  },
  "2025-04": {
    title: "The Apartment",
    summary: "Keys, boxes, and one plant that did not survive the move.",
    date: "2025-04-03",
    location: "Prague",
    notes:
      "We ate the first dinner on the floor because the table came a week later. Best meal of the year.",
    events: [
      { slug: "keys", title: "Keys", date: "2025-04-03", location: "Prague", photos: 4 },
      {
        slug: "floor-dinner",
        title: "Dinner on the Floor",
        photos: 5,
        notes: "The table came a week later. We have not eaten that well at it since.",
      },
      { slug: "the-plant", title: "The Plant That Didn't Make It", photos: 3 },
    ],
  },
  "2025-09": {
    title: "Salt and Sunburn",
    summary:
      "Our first trip together. Four days, one very small rental car, zero regrets.",
    location: "Istria, Croatia",
    notes:
      "You insisted we take the coastal road even though it added two hours. You were right. You are usually right about roads.",
    events: [
      {
        slug: "coast-road",
        title: "The Coastal Road",
        location: "Istria, Croatia",
        photos: 5,
        notes: "Two hours longer and worth every one of them.",
      },
      { slug: "rovinj", title: "Rovinj, Late", location: "Rovinj", photos: 5 },
      { slug: "cold-swim", title: "The Cold Swim", photos: 4 },
    ],
  },
  "2026-01": {
    title: "Snow Week",
    summary:
      "You learned to snowboard. I learned how many times a person can fall over and still be smug about it.",
    location: "Špindlerův Mlýn",
    notes: "Day three was the good one. Empty slope, no wind, the light going gold at four.",
    events: [
      { slug: "first-lesson", title: "First Lesson", photos: 5 },
      {
        slug: "day-three",
        title: "Day Three",
        photos: 5,
        notes: "Empty slope, no wind, the light going gold at four.",
      },
    ],
  },
  "2026-05": {
    title: "The Long Way Home",
    summary: "No plan, a full tank, and every detour we felt like taking.",
    location: "Somewhere in Moravia",
    events: [
      { slug: "no-plan", title: "No Plan", photos: 4 },
      { slug: "every-detour", title: "Every Detour", photos: 5 },
    ],
  },
};

/** The single blank event an unwritten month stands on. */
function blankEvent(monthLabel: string, year: number, i: number): WrittenEvent {
  return { slug: "01", title: `${monthLabel} ${year}`, photos: 3 + (i % 3) };
}

function buildEvent(monthId: string, entry: WrittenEvent): MemoryEvent {
  const dir = `/images/${monthId}/${entry.slug}`;
  const count = entry.photos ?? DEFAULT_EVENT_PHOTOS;

  return {
    id: `${monthId}/${entry.slug}`,
    monthId,
    slug: entry.slug,
    title: entry.title,
    date: entry.date,
    location: entry.location,
    notes: entry.notes,
    cover: {
      id: `${monthId}-${entry.slug}-cover`,
      src: `${dir}/cover.jpg`,
      alt: entry.title,
    },
    photos: Array.from({ length: count }, (_, i) => {
      const n = String(i + 1).padStart(2, "0");
      return {
        id: `${monthId}-${entry.slug}-${n}`,
        src: `${dir}/${n}.jpg`,
        alt: `${entry.title} — photo ${i + 1}`,
      };
    }),
  };
}

function buildMonth(i: number): Month {
  const offset = START_MONTH - 1 + i;
  const year = START_YEAR + Math.floor(offset / 12);
  const monthIndex = (offset % 12) + 1;
  const monthLabel = MONTH_NAMES[monthIndex - 1];
  const id = `${year}-${String(monthIndex).padStart(2, "0")}`;
  const entry = written[id];
  const events = entry?.events ?? [blankEvent(monthLabel, year, i)];

  return {
    id,
    year,
    monthIndex,
    monthLabel,
    title: entry?.title ?? `${monthLabel} ${year}`,
    summary: entry?.summary ?? "Still to be written.",
    date: entry?.date,
    location: entry?.location,
    notes: entry?.notes,
    events: events.map((event) => buildEvent(id, event)),
  };
}

const allMonths: Month[] = Array.from({ length: MONTH_COUNT }, (_, i) => buildMonth(i));

/**
 * Two anniversary years, twelve months each — September to August, not January
 * to December. lib/timeline's spine draws its ticks the same way.
 */
export const timeline: YearBlock[] = [
  { year: 2024, label: "Year One", months: allMonths.slice(0, 12) },
  { year: 2025, label: "Year Two", months: allMonths.slice(12) },
];
