/**
 * All site content lives here — static, hand-authored, no CMS.
 *
 * Photos are currently placeholders generated by scripts/generate-placeholders.mjs.
 * When real photos replace them, resize to ~1500-2000px on the longest edge
 * first (see REQUIREMENTS.md performance rules) — the covers become WebGL
 * textures and full-size originals burn GPU memory for nothing.
 */

export interface MemoryPhoto {
  id: string;
  src: string; // path under /public/images/...
  alt: string;
  caption?: string;
}

export interface Month {
  id: string; // "2024-03"
  year: number; // 2024
  monthIndex: number; // 1-12
  monthLabel: string; // "March"
  coverImage: string; // used by the 3D card
  title: string; // short milestone title, e.g. "Our First Trip"
  summary: string; // 1-2 sentence teaser shown on the card itself
  date?: string; // specific date, if there's one headline event
  location?: string;
  gallery: MemoryPhoto[]; // full photo set shown in the drawer
  notes?: string; // longer story text shown in the drawer
}

export interface YearBlock {
  year: number;
  label: string; // "Year One"
  months: Month[];
}

/** Builds the repetitive gallery entries for a month of placeholder photos. */
function placeholderGallery(monthId: string, count: number, alt: string): MemoryPhoto[] {
  return Array.from({ length: count }, (_, i) => {
    const n = String(i + 1).padStart(2, "0");
    return {
      id: `${monthId}-${n}`,
      src: `/images/${monthId}/${n}.jpg`,
      alt: `${alt} — photo ${i + 1}`,
    };
  });
}

export const timeline: YearBlock[] = [
  {
    year: 2024,
    label: "Year One",
    months: [
      {
        id: "2024-09",
        year: 2024,
        monthIndex: 9,
        monthLabel: "September",
        coverImage: "/images/2024-09/cover.jpg",
        title: "The First Night",
        summary:
          "A coffee that was supposed to take an hour and somehow took until the trams stopped running.",
        date: "2024-09-14",
        location: "Prague",
        gallery: placeholderGallery("2024-09", 5, "The first night"),
        notes:
          "Neither of us remembers who suggested walking to the river. What we do remember is standing on the bridge arguing about whether the swans were asleep, and the exact moment it stopped feeling like a first date.",
      },
      {
        id: "2024-12",
        year: 2024,
        monthIndex: 12,
        monthLabel: "December",
        coverImage: "/images/2024-12/cover.jpg",
        title: "Rain and Ramen",
        summary:
          "The grey month. We stayed inside and made it the best one anyway.",
        gallery: placeholderGallery("2024-12", 4, "Rain and ramen"),
      },
      {
        id: "2025-04",
        year: 2025,
        monthIndex: 4,
        monthLabel: "April",
        coverImage: "/images/2025-04/cover.jpg",
        title: "The Apartment",
        summary: "Keys, boxes, and one plant that did not survive the move.",
        date: "2025-04-03",
        location: "Prague",
        gallery: placeholderGallery("2025-04", 5, "The apartment"),
        notes:
          "We ate the first dinner on the floor because the table came a week later. Best meal of the year.",
      },
    ],
  },
  {
    year: 2025,
    label: "Year Two",
    months: [
      {
        id: "2025-09",
        year: 2025,
        monthIndex: 9,
        monthLabel: "September",
        coverImage: "/images/2025-09/cover.jpg",
        title: "Salt and Sunburn",
        summary:
          "Our first trip together. Four days, one very small rental car, zero regrets.",
        location: "Istria, Croatia",
        gallery: placeholderGallery("2025-09", 7, "Salt and sunburn"),
        notes:
          "You insisted we take the coastal road even though it added two hours. You were right. You are usually right about roads.",
      },
      {
        id: "2026-01",
        year: 2026,
        monthIndex: 1,
        monthLabel: "January",
        coverImage: "/images/2026-01/cover.jpg",
        title: "Snow Week",
        summary:
          "You learned to snowboard. I learned how many times a person can fall over and still be smug about it.",
        location: "Špindlerův Mlýn",
        gallery: placeholderGallery("2026-01", 6, "Snow week"),
        notes: "Day three was the good one. Empty slope, no wind, the light going gold at four.",
      },
      {
        id: "2026-05",
        year: 2026,
        monthIndex: 5,
        monthLabel: "May",
        coverImage: "/images/2026-05/cover.jpg",
        title: "The Long Way Home",
        summary: "No plan, a full tank, and every detour we felt like taking.",
        location: "Somewhere in Moravia",
        gallery: placeholderGallery("2026-05", 6, "The long way home"),
      },
    ],
  },
];
