/**
 * All site content lives here — static, hand-authored, no CMS.
 *
 * Photos are currently placeholders generated by scripts/generate-placeholders.mjs.
 * When real photos replace them, resize to ~1500-2000px on the longest edge
 * first (see REQUIREMENTS.md performance rules) — the covers become WebGL
 * textures and full-size originals burn GPU memory for nothing.
 */

export interface MemoryPhoto {
  id: string;
  src: string; // path under /public/images/...
  alt: string;
  caption?: string;
}

export interface Month {
  id: string; // "2024-03"
  year: number; // 2024
  monthIndex: number; // 1-12
  monthLabel: string; // "March"
  coverImage: string; // used by the 3D card
  title: string; // short milestone title, e.g. "Our First Trip"
  summary: string; // 1-2 sentence teaser shown on the card itself
  date?: string; // specific date, if there's one headline event
  location?: string;
  gallery: MemoryPhoto[]; // full photo set shown in the drawer
  notes?: string; // longer story text shown in the drawer
}

export interface YearBlock {
  year: number;
  label: string; // "Year One"
  months: Month[];
}

const MONTH_NAMES = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];

/** The run starts here and covers every month since, with no gaps. */
const START_YEAR = 2024;
const START_MONTH = 9;
const MONTH_COUNT = 24;

/**
 * The months that have been written.
 *
 * Everything else in the two years is generated below as a placeholder, so the
 * timeline is continuous from the first month to the last — an unwritten month
 * is a month waiting to be written, not a month missing from the story. Replace
 * an entry here as each one gets its photos and its text.
 */
const written: Record<
  string,
  Omit<Partial<Month>, "gallery"> & { photos?: number }
> = {
  "2024-09": {
    title: "The First Night",
    summary:
      "A coffee that was supposed to take an hour and somehow took until the trams stopped running.",
    date: "2024-09-14",
    location: "Prague",
    photos: 5,
    notes:
      "Neither of us remembers who suggested walking to the river. What we do remember is standing on the bridge arguing about whether the swans were asleep, and the exact moment it stopped feeling like a first date.",
  },
  "2024-12": {
    title: "Rain and Ramen",
    summary: "The grey month. We stayed inside and made it the best one anyway.",
    photos: 4,
  },
  "2025-04": {
    title: "The Apartment",
    summary: "Keys, boxes, and one plant that did not survive the move.",
    date: "2025-04-03",
    location: "Prague",
    photos: 5,
    notes:
      "We ate the first dinner on the floor because the table came a week later. Best meal of the year.",
  },
  "2025-09": {
    title: "Salt and Sunburn",
    summary:
      "Our first trip together. Four days, one very small rental car, zero regrets.",
    location: "Istria, Croatia",
    photos: 7,
    notes:
      "You insisted we take the coastal road even though it added two hours. You were right. You are usually right about roads.",
  },
  "2026-01": {
    title: "Snow Week",
    summary:
      "You learned to snowboard. I learned how many times a person can fall over and still be smug about it.",
    location: "Špindlerův Mlýn",
    photos: 6,
    notes:
      "Day three was the good one. Empty slope, no wind, the light going gold at four.",
  },
  "2026-05": {
    title: "The Long Way Home",
    summary: "No plan, a full tank, and every detour we felt like taking.",
    location: "Somewhere in Moravia",
    photos: 6,
  },
};

/** Photos a month has while its pictures are placeholders. Mirrored in scripts/generate-placeholders.mjs. */
function photoCount(id: string, i: number): number {
  return written[id]?.photos ?? 3 + (i % 3);
}

/** Builds the repetitive gallery entries for a month of placeholder photos. */
function placeholderGallery(monthId: string, count: number, alt: string): MemoryPhoto[] {
  return Array.from({ length: count }, (_, i) => {
    const n = String(i + 1).padStart(2, "0");
    return {
      id: `${monthId}-${n}`,
      src: `/images/${monthId}/${n}.jpg`,
      alt: `${alt} — photo ${i + 1}`,
    };
  });
}

function buildMonth(i: number): Month {
  const offset = START_MONTH - 1 + i;
  const year = START_YEAR + Math.floor(offset / 12);
  const monthIndex = (offset % 12) + 1;
  const monthLabel = MONTH_NAMES[monthIndex - 1];
  const id = `${year}-${String(monthIndex).padStart(2, "0")}`;
  const entry = written[id];

  return {
    id,
    year,
    monthIndex,
    monthLabel,
    coverImage: `/images/${id}/cover.jpg`,
    title: entry?.title ?? `${monthLabel} ${year}`,
    summary: entry?.summary ?? "Still to be written.",
    date: entry?.date,
    location: entry?.location,
    gallery: placeholderGallery(id, photoCount(id, i), entry?.title ?? `${monthLabel} ${year}`),
    notes: entry?.notes,
  };
}

const allMonths: Month[] = Array.from({ length: MONTH_COUNT }, (_, i) => buildMonth(i));

/**
 * Two anniversary years, twelve months each — September to August, not January
 * to December. lib/timeline's spine draws its ticks the same way.
 */
export const timeline: YearBlock[] = [
  { year: 2024, label: "Year One", months: allMonths.slice(0, 12) },
  { year: 2025, label: "Year Two", months: allMonths.slice(12) },
];
